include( ${CMAKE_CURRENT_LIST_DIR}/../../root.cmake )

include( ${RTIO_SDK_ROOT_DIR}/libraries/standard/coreRTIO/rtioFilePaths.cmake )
include( ${RTIO_SDK_ROOT_DIR}/platform/posix/posixFilePaths.cmake )

set( RTIO_SDK_SOURCES
     ${RTIO_SOURCES}
     ${SOCKETS_SOURCES}
     ${OPENSSL_TRANSPORT_SOURCES}
     ${COMMON_OS_SOURCES} )

set( RTIO_SDK_INCLUDE_DIRS
     ${RTIO_INTERFACE_INCLUDE_DIR}
     ${TRANSPORT_INTERNEL_INCLUDE_PUBLIC_DIRS}
     ${COMMON_TRANSPORT_OPENSSL_INCLUDE_PUBLIC_DIRS}
     ${COMMON_OS_INCLUDE_PUBLIC_DIRS}
     ${RTIO_INCLUDE_INTERNEL_DIRS}
     ${RTIO_INCLUDE_PUBLIC_DIRS} )
